x-shared_environment: &shared_environment
  LOG_LEVEL: ${LOG_LEVEL:-info}
  DATABASE_URL: postgresql://user:password@db:5432/discsim

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: discsim-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      <<: *shared_environment
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: discsim
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d discsim" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  data:
