services:
  web:
    image: ghcr.io/cegis-org/discsim:sha-fa9f907  # Use the GHCR image here
    container_name: discsim-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Optional: only keep if needed for live updates or sharing files
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    command: python api/run.py
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  streamlit:
    image: ghcr.io/cegis-org/discsim:sha-fa9f907  # Also use the GHCR image for the frontend
    container_name: discsim-frontend
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Optional, same as above
    restart: always
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
      - API_BASE_URL=${API_BASE_URL}
    command: streamlit run dashboard/app.py
    depends_on:
      web:
        condition: service_healthy
      db:
        condition: service_healthy

volumes:
  postgres_data:
  data:
