services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/init:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    networks:
      - app-network
    entrypoint: ["/docker-entrypoint-initdb.d/entrypoint.sh"]

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - LOG_LEVEL=${LOG_LEVEL}
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - API_BASE_URL=${API_BASE_URL}
    depends_on:
      - api
    ports:
      - "8501:8501"
    networks:
      - app-network
    command: ["streamlit", "run", "dashboard/app.py", "--server.port=8501", "--server.address=0.0.0.0"]

volumes:
  postgres_data:

networks:
  app-network:
