[client]
toolbarMode = "minimal"

[browser]
gatherUsageStats = false


#primaryColor = #136a9a
#secondaryColor = #3b8e51
[theme]
primaryColor = "#136a9a"

[server]
runOnSave = true
fileWatcherType = "auto"